### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by atommixz** [kidig/vk-audio-sync#3]
```
$ python2 vk_audiosync.py 
start...
Download Sir Flansi - Sin Luz (instrumental)...
Traceback (most recent call last):
  File "vk_audiosync.py", line 118, in <module>
    main()
  File "vk_audiosync.py", line 112, in main
    download_audio_files()
  File "vk_audiosync.py", line 96, in download_audio_files
    g.urlgrab(url, filename=filepath)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 976, in urlgrab
    return self._retry(opts, retryfunc, url, filename)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 880, in _retry
    r = apply(func, (opts,) + args, {})
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 962, in retryfunc
    fo = PyCurlFileObject(url, filename, opts)
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1056, in __init__
    self._do_open()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1308, in _do_open
    self._do_grab()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1438, in _do_grab
    self._do_perform()
  File "/usr/lib/python2.7/site-packages/urlgrabber/grabber.py", line 1301, in _do_perform
    raise err
urlgrabber.grabber.URLGrabError: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
```

**Comment by atommixz** [comment]
```
$ pip2 freeze
Beaker==1.8.0
chardet==2.3.0
distorm3==3.3.0
Mako==1.0.3
MarkupSafe==0.23
mutagen==1.31
packaging==16.0
pycurl==7.21.5
pygobject==3.18.2
pyinotify==0.9.6
pyparsing==2.0.7
python-dateutil==2.4.2
python-libtorrent==1.0.8
python-musicbrainz==0.0.0
requests==2.9.1
six==1.10.0
syncthing-gtk==0.8.2
urlgrabber==3.9.1
vk-api==7.0
VKMusic==0.1.3
zenmap==7.1
```

**Comment by kidig** [comment]
выкатил изменения в ветке master, должно работать.
если будут какие ошибки, прошу сообщить.

thx!

**Comment by whoizit** [comment]
```
$ python2 ./vkaudiosync.py 
Traceback (most recent call last):
  File "./vkaudiosync.py", line 173, in <module>
    main()
  File "./vkaudiosync.py", line 166, in main
    download_tracks(tracks, config.MUSIC_PATH)
  File "./vkaudiosync.py", line 99, in download_tracks
    track['artist'] = clean_audio_tag(track.get('artist'))
  File "./vkaudiosync.py", line 44, in clean_audio_tag
    tag = h.unescape(tag)
  File "/usr/lib/python2.7/HTMLParser.py", line 448, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by kidig** [comment]
Ох, уж эти спецсимволы в названиях треков...

Можешь вставить в vkaudiosync.py перед строкой 44:
`print "TAG: ", tag`
и скинуть вывод?

**Comment by whoizit** [comment]
```
    print "TAG: ", tag
    tag = h.unescape(tag)
    print "TAG: ", tag
    tag = h.unescape(tag) # need to unescape unescaped entities
    print "TAG: ", tag
```

```

$ python2 vkaudiosync.py
TAG:  None
Traceback (most recent call last):
  File "vkaudiosync.py", line 176, in <module>
    main()
  File "vkaudiosync.py", line 169, in main
    download_tracks(tracks, config.MUSIC_PATH)
  File "vkaudiosync.py", line 102, in download_tracks
    track['artist'] = clean_audio_tag(track.get('artist'))
  File "vkaudiosync.py", line 45, in clean_audio_tag
    tag = h.unescape(tag)
  File "/usr/lib/python2.7/HTMLParser.py", line 448, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by whoizit** [comment]
```
    for track in tracks:
        pp = pprint.PrettyPrinter(indent=4)
        pp.pprint(track)
        track['aid'] = str(track.get('aid'))
        track['artist'] = clean_audio_tag(track.get('artist'))
        track['title'] = clean_audio_tag(track.get('title'))

```

```
$ python2 vkaudiosync.py
{   u'382536349': u'376142608',
    u'Sin Luz (instrumental)': u'Little Moment',
    u'Sir Flansi': u'Omar Linx',
    u'http://cs422219.vk.me/u71419167/audios/c505454e21a0.mp3?extra=sh7Wg0IhzuI95h9ChXu-hGbvyVJSG-hzYI7PINuzdCvSjxEegzyIozggnC-oO45mdInK3N_nfbUVmtw2J3V4-lmsgIK78Izi': u'http://cs5107.vk.me/u6758080/audios/f18f1e809ff6.mp3?extra=tlcTqX5O63ZcqdyBJNSZ2ds39HI-c4xnycJCX9OPZd3F2UdMX00vgmWk7wi0kHXsmhTzqV-a56qq7KxtbjO9GWrd7Vs4tozE'}
TAG:  None
Traceback (most recent call last):
...
```
